### ISSUE TITLE
Sample of use gcs-helper with Kaltura VOD

### ISSUE THREAD

**Issue by cwichoski** [NYTimes/gcs-helper#11]
Hi

Can you provide some samples on how to use gcs-helper with Kaltura VOD?

best regards

**Comment by fsouza** [comment]
Hi @cwichoski, I apologize for such a ridiculous delay in responding this ticket. Here's an example (includes ``nginx.conf`` and ``docker-compose.yml`` for running locally): https://github.com/fsouza/gcs-helper-vod-module-example

I'll also link that example in the README file. Thanks for opening this issue.
