### ISSUE TITLE
oauth2: cannot fetch token: 400 Bad Request

### ISSUE THREAD

**Issue by sqdk** [NYTimes/gcs-helper#14]
Hi,

I was testing out the container, and I cannot seem to get a hole through to GCS with a service account credential file.

I have set GOOGLE_APPLICATION_CREDENTIALS to point to my json file. And I have verified that my key has access to the specified resources.

I modified the following function in proxy.go to give some more output:
```
func objectHandle(c *Config, client *storage.Client, r *http.Request) *storage.ObjectHandle {
	bucketName := c.BucketName
	objectName := strings.TrimLeft(r.URL.Path, "/")
	if c.Proxy.BucketOnPath {
		pos := strings.Index(objectName, "/")
		bucketName = objectName[:pos]
		objectName = objectName[pos+1:]
	}

	fmt.Printf("BucketName: %s ObjName: %s\n", bucketName, objectName)

	rc, err := client.Bucket(bucketName).Object(objectName).NewReader(context.Background())
	if err != nil {
		fmt.Println("Got error reading file from GCS:")
		fmt.Println(err)
	}
	slurp, err := ioutil.ReadAll(rc)
	rc.Close()
	if err != nil {
		fmt.Println("Got error reading byte stream:")
		fmt.Println(err)
	}
	fmt.Println("file contents:", slurp)

	return client.Bucket(bucketName).Object(objectName)
}
```

And i get the following output:
```
$ docker run -e "GCS_HELPER_BUCKET_NAME=my-bucket-name" -e "GOOGLE_APPLICATION_CREDENTIALS=/credentials.json" -p 8080:8080 -it t  
INFO[0000] Listening on [::]:8080...                    
BucketName: my-bucket-name ObjName: test_report/index.html
Got error reading file from GCS:
Get https://storage.googleapis.com/my-bucket-name/test_report/index.html: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_scope",
  "error_description": "Empty or missing scope not allowed."
}
```

Is this something anyone have seen before? I have never had to set any scopes before when I previously used service accounts as json files. 

If anyone can point me in the right direction, I'll volunteer to help update the documentation accordingly. I tried googling around, but most things I found are talking about Compute Instance scopes which does not sound applicable.

**Comment by fsouza** [comment]
Hey @sqdk, thanks for opening this issue. I wonder if there's something going on with that credentials file. Is it for a service account? Does gsutil work with that file?

```
export GOOGLE_APPLICATION_CREDENTIALS=/credentials.json
gsutil cp gs://my-bucket-name/test_report/index.html /tmp
```

**Comment by sqdk** [comment]
@fsouza sorry for the dupe!

The credentials is a service account, yes. And great idea to test locally. 

I just checked that the credential file works with gsutil:
```
$ gcloud auth activate-service-account --key-file credentials.json
Activated service account credentials for: [OMITTED]
$ gsutil ls                                                       
gs://my-bucket-name/
$ gsutil cp gs://my-bucket-name/test_report/index.html .
Copying gs://my-bucket-name/test_report/index.html...
/ [1 files][ 97.3 KiB/ 97.3 KiB]                                                
Operation completed over 1 objects/97.3 KiB.
```

This leads me to believe that SOMETHING is confusing the library as to what auth method to use. It seems to look for something it shouldn't.

Do you usually run this in a container or a VM?

**Comment by fsouza** [comment]
Yeah I just realized we've never ran this with a SA (we run it locally with user accounts and in GCE with roles), but we assumed it would work.

Let me give it a shot then I'll get back to you. Sorry about that.

**Comment by sqdk** [comment]
Well, good to know I am not going crazy!

Thanks for helping me out. Really appreciated!

**Comment by sqdk** [comment]
@fsouza It all makes sense then! Thanks for the quick reply!

I got my test setup ready so I'll check it out right now.

**Comment by fsouza** [comment]
@sqdk thanks for confirming!
